---
- name: Required packages are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - python3-psycopg2
  - postgresql-{{ postgres_version }}

- name: PostgreSQL cluster main is present
  command: pg_createcluster {{ postgres_version }} main
  args:
    creates: /var/lib/postgresql/{{ postgres_version }}/main

- name: PostgreSQL is configured to listen on 0.0.0.0
  lineinfile:
    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regexp: "^listen_addresses = "
    line: "listen_addresses = '*'"
  notify: Restart postgres

- name: Backup directory is present
  file:
    name: /var/local/backups
    state: directory
    owner: root
    group: postgres
    mode: 0770

- name: Install backup script for all databases
  copy:
    content: "#!/bin/sh\npg_dumpall | gzip > /var/local/backups/pg_dumpall.$(date +%Y-%m-%d-%H:%M:%S).sql.gz\n"
    dest: /usr/local/sbin/awesto-pgbackupall.sh
    owner: postgres
    group: postgres
    mode: 0700

- name: Install backup cronjob for all databases
  cron:
    name: Postgres backup (all databases)
    job: "/usr/local/sbin/awesto-pgbackupall.sh"
    hour: 1
    minute: 30
    user: postgres

- name: Install tmpreaper
  apt:
    pkg: tmpreaper
    state: installed

- name: Disable tmpreaper warning
  lineinfile:
    dest: /etc/tmpreaper.conf
    line: SHOWWARNING=false
    regexp: ^SHOWWARNING=

- name: Install tmpreaper cronjob
  cron:
    name: Postgres backup cleanup
    job: "/usr/sbin/tmpreaper --mtime {{ postgres_backup_retention_time|default('30d') }} /var/local/backups/"
    special_time: daily

- include: databases.yml
